services:
  db:
    image: postgres:12.0-alpine
    container_name: messenger_db
    ports:
      - 0.0.0.0:35432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=messenger
    networks:
      - messenger-network
    volumes:
      - ./_data:/var/lib/postgresql/data

networks:
  messenger-network:
    name: messenger-network
