services:
  db:
    image: postgres:12.0-alpine
    container_name: movie
    restart: always
    ports:
      - 0.0.0.0:45432:5432
    env_file:
      - .env
    networks:
      - movie-network
    volumes:
      - ./_data:/var/lib/postgresql/data

networks:
  movie-network:
    name: movie-network
