"""empty message

Revision ID: 5f7f58346ab5
Revises: 8e804cf7b95a
Create Date: 2021-09-17 13:33:22.210206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f7f58346ab5'
down_revision = '8e804cf7b95a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors_2_films',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actors_id', sa.Integer(), nullable=True),
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actors_id'], ['actors.id'], name=op.f('fk__actors_2_films__actors_id__actors')),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], name=op.f('fk__actors_2_films__film_id__films')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__actors_2_films'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actors_2_films')
    # ### end Alembic commands ###
