"""Initial

Revision ID: 793d91880b17
Revises: 
Create Date: 2021-09-07 21:55:40.504788

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "793d91880b17"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__users")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
