"""empty message

Revision ID: bca575ec07c3
Revises: 793d91880b17
Create Date: 2021-09-09 18:56:57.049500

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bca575ec07c3"
down_revision = "793d91880b17"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("name", sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "name")
    # ### end Alembic commands ###
