"""empty message

Revision ID: 3af1b6244814
Revises: b4a94e356e42
Create Date: 2021-09-20 21:13:17.869791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3af1b6244814'
down_revision = 'b4a94e356e42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
