"""empty message

Revision ID: 64914d7a8aa4
Revises: 3af1b6244814
Create Date: 2021-09-20 21:18:22.035366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64914d7a8aa4'
down_revision = '3af1b6244814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
