"""empty message

Revision ID: 7ef0b1ee5165
Revises: 64914d7a8aa4
Create Date: 2021-09-20 21:19:21.104493

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7ef0b1ee5165"
down_revision = "64914d7a8aa4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
