"""empty message

Revision ID: 8e804cf7b95a
Revises: bca575ec07c3
Create Date: 2021-09-14 20:01:28.480010

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8e804cf7b95a"
down_revision = "bca575ec07c3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "actors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__actors")),
    )
    op.create_table(
        "films",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=80), nullable=True),
        sa.Column("rating", sa.String(length=80), nullable=True),
        sa.Column("genre", sa.String(length=80), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__films")),
    )
    op.drop_table("users")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=80), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk__users"),
    )
    op.drop_table("films")
    op.drop_table("actors")
    # ### end Alembic commands ###
