"""empty message

Revision ID: b4a94e356e42
Revises: 5f7f58346ab5
Create Date: 2021-09-20 19:51:44.034685

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b4a94e356e42"
down_revision = "5f7f58346ab5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
